strat = ["Long Call",
         "Short Call",
         "Long Put",
         "Short Put",
         "Bull Call Spread",
         "Bull Put Spread",
         "Bear Call Spread",
         "Bear Put Spread",
         "Top Strip",
         "Bottom Strip",
         "Top Strap",
         "Bottom Strap",
         "Top Straddle",
         "Bottom Straddle",
         "Top Strangle",
         "Bottom Strangle",
         "Top Butterfly",
         "Bottom Butterfly",
         "Top Iron Condor",
         "Bottom Iron Condor"]
